-- FastOffres MVP schema
-- Run this in the Supabase SQL editor before connecting the app/scanner.

create table if not exists public.sources (
  id text primary key,
  brand text not null,
  city text not null default 'Bordeaux',
  url text not null,
  type text not null default 'official_site',
  priority integer not null default 100,
  enabled boolean not null default true,
  keywords text[] not null default '{}',
  last_scan_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.offers (
  id bigint generated by default as identity primary key,
  brand text not null,
  title text not null,
  description text,
  price text,
  old_price text,
  badge text not null default 'À vérifier',
  badge_icon text not null default 'visibility',
  category text not null default 'new',
  city text not null default 'Bordeaux',
  image text,
  distance text,
  source_url text,
  source_id text,
  source_type text,
  status text not null default 'pending' check (status in ('pending', 'published', 'expired', 'rejected')),
  confidence_score integer not null default 50 check (confidence_score between 0 and 100),
  detected_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_id, title)
);

alter table public.sources enable row level security;
alter table public.offers enable row level security;

create policy "Public can read enabled sources"
  on public.sources
  for select
  using (enabled = true);

create policy "Public can read published offers"
  on public.offers
  for select
  using (status = 'published');

create index if not exists offers_status_city_idx on public.offers (status, city);
create index if not exists offers_category_idx on public.offers (category);
create index if not exists offers_last_seen_idx on public.offers (last_seen_at desc);